services:
  - type: web
    name: campusmind-rag-pdf-qa
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: MISTRAL_API_KEY
        sync: false
